/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#e1e0ff',
        'inverse-on-surface': '#f0f1f1',
        'secondary-fixed': '#e3e1ec',
        'on-tertiary-fixed': '#07006c',
        'inverse-surface': '#2f3131',
        'inverse-primary': '#bec6e0',
        'surface-container': '#eeeeee',
        'surface-container-lowest': '#ffffff',
        'surface': '#f9f9f9',
        'background': '#f9f9f9',
        'on-secondary-fixed-variant': '#46464e',
        'secondary': '#5d5e66',
        'on-surface': '#1a1c1c',
        'outline': '#76777d',
        'on-secondary-container': '#63646c',
        'tertiary-fixed-dim': '#c0c1ff',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'tertiary': '#000000',
        'surface-container-low': '#f3f3f3',
        'primary-fixed-dim': '#bec6e0',
        'surface-bright': '#f9f9f9',
        'primary-container': '#131b2e',
        'surface-dim': '#dadada',
        'surface-container-highest': '#e2e2e2',
        'on-secondary-fixed': '#1a1b22',
        'primary': '#000000',
        'on-background': '#1a1c1c',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#3f465c',
        'tertiary-container': '#07006c',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-tint': '#565e74',
        'surface-container-high': '#e8e8e8',
        'on-primary': '#ffffff',
        'on-primary-container': '#7c839b',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'on-tertiary-container': '#7073ff',
        'surface-variant': '#e2e2e2',
        'on-surface-variant': '#45464d',
        'secondary-container': '#e3e1ec',
        'on-primary-fixed': '#131b2e',
        'primary-fixed': '#dae2fd',
        'outline-variant': '#c6c6cd',
        'secondary-fixed-dim': '#c6c5cf',
        // Compatibility shades for app components
        ink: {
          50: '#f9f9f9',
          100: '#f3f3f3',
          200: '#e2e2e2',
          300: '#c6c6cd',
          400: '#76777d',
          500: '#5d5e66',
          600: '#45464d',
          700: '#2f3131',
          800: '#1a1c1c',
          900: '#000000',
          950: '#000000',
        },
        accent: {
          50: '#f9f9f9',
          100: '#e2e2e2',
          200: '#c6c6cd',
          300: '#76777d',
          400: '#45464d',
          500: '#000000',
          600: '#1a1c1c',
          700: '#07006c',
          800: '#000000',
          900: '#000000',
          950: '#000000',
        },
        danger: {
          50: '#fff5f5',
          100: '#ffdad6',
          400: '#ba1a1a',
          500: '#ba1a1a',
          600: '#93000a',
          700: '#93000a',
        },
        success: {
          500: '#16a34a',
          600: '#15803d',
        },
        warning: {
          500: '#d97706',
          600: '#b45309',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        gutter: '24px',
        base: '4px',
        'container-max': '1440px',
      },
      fontFamily: {
        'display-lg': ['var(--font-display)', 'Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg': ['var(--font-display)', 'Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-md': ['var(--font-display)', 'Plus Jakarta Sans', 'sans-serif'],
        button: ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-display)', 'Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        sans: ['var(--font-inter)', 'Inter', 'sans-serif'],
        display: ['var(--font-display)', 'Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        button: ['14px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        '2xs': ['10px', { lineHeight: '1.2' }],
      },
      boxShadow: {
        soft: '0 1px 2px 0 rgba(0,0,0,0.05)',
        card: '0 4px 20px -4px rgba(0,0,0,0.08)',
        pop: '0 10px 30px -10px rgba(0,0,0,0.15)',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%) rotate(30deg)' },
          '100%': { transform: 'translateX(100%) rotate(30deg)' },
        },
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        shimmer: 'shimmer 3s infinite',
        'fade-in': 'fade-in 0.25s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
      },
    },
  },
  plugins: [],
};

export default config;